### ISSUE TITLE
Some rpc also throw rate limit error

### ISSUE THREAD

**Issue by fewensa** [helix-bridge/helixconf#28]
```

  console.error
    Error: missing revert data (action="call", data=null, reason=null, transaction={ "data": "0x31c3ac91359a4580452fcbdeb01eb434635715abbe8dc9edc9627dfb1e53593a68e89f9a", "to": "0x61B6B8c7C00aA7F060a2BEDeE6b11927CC9c3eF1" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.13.2)
        at makeError (/home/runner/work/helixconf/helixconf/generated/typescript/node_modules/ethers/src.ts/utils/errors.ts:694:21)
        at getBuiltinCallException (/home/runner/work/helixconf/helixconf/generated/typescript/node_modules/ethers/src.ts/abi/abi-coder.ts:118:21)
        at Function.getBuiltinCallException (/home/runner/work/helixconf/helixconf/generated/typescript/node_modules/ethers/src.ts/abi/abi-coder.ts:235:16)
        at JsonRpcProvider.getRpcError (/home/runner/work/helixconf/helixconf/generated/typescript/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:989:32)
        at /home/runner/work/helixconf/helixconf/generated/typescript/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:563:45
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      code: 'CALL_EXCEPTION',
      action: 'call',
      data: null,
      reason: null,
      transaction: {
        to: '0x61B6B8c7C00aA7F060a2BEDeE6b11927CC9c3eF1',
        data: '0x31c3ac91359a4580452fcbdeb01eb434635715abbe8dc9edc9627dfb1e53593a68e89f9a'
      },
      invocation: null,
      revert: null,
      shortMessage: 'missing revert data',
      info: {
        error: { code: -32016, message: 'over rate limit' },
        payload: { method: 'eth_call', params: [Array], id: 65, jsonrpc: '2.0' }
      }
    }

      168 |     ], [remoteLzId, localApp]);
      169 |
    > 170 |     const sender = await this.contract['remoteAppSenders'](hash).catch(e => console.error(e));
          |                                                                                     ^
      171 |     return sender.toLowerCase();
      172 |   }
      173 | }

      at error (tests/common/contracts.ts:170:85)
      at LayerZeroMessagerContract.remoteAppSender (tests/common/contracts.ts:170:20)
      at LayerZeroMessager.remoteAppIsSender (tests/common/messager.ts:131:39)
      at Bridge.isSourceAppConnectedTarget (tests/common/bridge.ts:155:12)
      at Object.<anonymous> (tests/online.couples.test.ts:42:42)
```

```

  console.error
    Error: missing revert data (action="call", data=null, reason=null, transaction={ "data": "0x90f1f17b545d21d5f3c07514f7f7d034b9748dbb55dd8f5d6e208754cb9ae2a7ed6f7f4a", "to": "0xbA5D580B18b6436411562981e02c8A9aA1776D10" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.13.2)
        at makeError (/home/runner/work/helixconf/helixconf/generated/typescript/node_modules/ethers/src.ts/utils/errors.ts:694:21)
        at getBuiltinCallException (/home/runner/work/helixconf/helixconf/generated/typescript/node_modules/ethers/src.ts/abi/abi-coder.ts:118:21)
        at Function.getBuiltinCallException (/home/runner/work/helixconf/helixconf/generated/typescript/node_modules/ethers/src.ts/abi/abi-coder.ts:235:16)
        at JsonRpcProvider.getRpcError (/home/runner/work/helixconf/helixconf/generated/typescript/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:989:32)
        at /home/runner/work/helixconf/helixconf/generated/typescript/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:563:45
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      code: 'CALL_EXCEPTION',
      action: 'call',
      data: null,
      reason: null,
      transaction: {
        to: '0xbA5D580B18b6436411562981e02c8A9aA1776D10',
        data: '0x90f1f17b545d21d5f3c07514f7f7d034b9748dbb55dd8f5d6e208754cb9ae2a7ed6f7f4a'
      },
      invocation: null,
      revert: null,
      shortMessage: 'missing revert data',
      info: {
        error: { code: -32016, message: 'over rate limit' },
        payload: { method: 'eth_call', params: [Array], id: 55, jsonrpc: '2.0' }
      }
    }

      320 |   async tokenInfo(remoteChainId: bigint, sourceToken: string, targetToken: string): Promise<Lnv3TokenInfo> {
      321 |     const encode = this.tokenKey(remoteChainId, sourceToken, targetToken);
    > 322 |     return await this.contract['tokenInfos'](encode).catch(e => console.error(e));
          |                                                                         ^
      323 |   }
      324 |
      325 |   async indexToTokenKey(index: number): Promise<string> {

      at error (tests/common/contracts.ts:322:73)
      at Lnv3BridgeContract.tokenInfo (tests/common/contracts.ts:322:12)
      at Lnv3BridgeContract.tokenRegistered (tests/common/contracts.ts:308:23)
      at BridgeProtocol.tokenRegistered (tests/common/bridge.ts:69:33)
      at Object.<anonymous> (tests/online.couples.test.ts:58:31)

```

**Comment by fewensa** [comment]
Fixed #21
